
[profile.default]
optimizer = true
optimizer_runs = 200
via_ir = true              # IR pipeline often shrinks runtime code
bytecode_hash = "none"     # drops metadata hash (~40â€“50 bytes)
cbor_metadata = false      # keep artifacts small; not in runtime, but good hygiene
chain_id = 8453

src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
base = "${BASE_HTTP_URL_1}"

